:concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY", 10).to_i %>
:queues:
  - [email_sender_api_production_critical, 3]
  - [email_sender_api_production_default, 2]
  - [email_sender_api_production_low, 1]
  - [critical, 3]
  - [default, 2]
  - [low, 1]





